sudo: required
services:
  - docker

before_install:
  - docker build -t herogarp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true herogarp/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-826418236555"
  bucket_path: "docker-react"
  on:
    branch: master
  acces_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"